# Starter pipeline
- task: Application security testing@2020
  inputs:
    projectName: 'Vulnado'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'Checkmarx CxSAST'
    fullTeamName: 'CxServer\SP\EMEA\LATAM\kmhcorp2'
    enableDependencyScan: false
- task: Application security testing@2020
  inputs:
    projectName: 'PoC desde Azure'
    enableSastScan: true
    CheckmarxService: 'Postobon Checkmarx Instance PoC'
    enableDependencyScan: false
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
