# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Checkmarx AST@2
  inputs:
    CheckmarxService: 'Checkmarx One'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'nfr_lugapel-ast'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
